device: cpu
fps: 30
match_thresh: 0.8
min_box_area: 10
save_result: True
track_buffer: 30
track_thresh: 0.5
aspect_ratio_thresh: 1.6
ckpt: /home/altaf/Everyday_tasks/face_rec/Face-Recognition-System/face_tracking/pretrained/bytetrack_x_mot17.pth.tar
fp16: True
